### ISSUE TITLE
CY-01-009 Cyph Admin Interface is using Default Credentials (Critical) 

### ISSUE THREAD

**Issue by cure53** [cyph/cyph#37]
Similar to the issue reported in [CY-01-008](https://github.com/cyph/cyph/issues/37), the admin interface of the Coturn server software is exposed to the Internet and can be accessed with default credentials.

**Tested and working credentials:**

```
user:bayaz
password: magi
```

**Default credentials in docs:**
https://code.google.com/p/coturn/wiki/CoturnConfig#Coturn_installation

**Affected Installations:**
- https://ice.cyph.com:3478/
- https://ice.cyph.com:3479/ 
- https://ice.cyph.com:5349/
- https://ice.cyph.com:5350/ 

It is highly recommended to change the default credentials and use a strong username and password combination. It is further recommended to prohibit the admin panel from allowing arbitrary external connections for access. By doing so, the attack can be fully mitigated.

**Comment by buu700** [comment]
As a note for future reference, we have since stopped hosting the vulnerable coturn AMI instance in question. As of March 2016, we use [Twilio's STUN/TURN PaaS](https://www.twilio.com/stun-turn) for network traversal.
