### ISSUE TITLE
SSL / TLS cert issues in Chrome

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [cyph/cyph#53]
Hi Cyphers,

There is a problem on the official website's SSL / TLS certificate for the Chrome browser (maybe others as well).

If you browse to:
- https://cyph.ws/, you'll get a Chrome certificate error `NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN`
- https://www.cyph.ws/, you'll see the app load for a short bit and then get directed to the non-www domain and get the issue described above

This is the part of the code that triggers the redirect on the www version.
```
/* Set pin on www subdomain on first use, then force naked domain */
if (location.host.indexOf('www.') === 0) {
	location.host	= location.host.replace('www.', '');
	return;
}
```

This only happens in incognito mode or on browsers that haven't been on cyph.ws before (fresh OSX installs).

My guess is that this is due to the HTTPS preload setup for cyph.ws:

https://hstspreload.org/?domain=cyph.ws

The certificated I get:
- normal mode (cached from HTTPS preload I guess), is valid from 30 August 2015 to 6 September 2017
- incognito (new certificate that is broken), is valid from 17 July 2017 (today!) to 9 September 2019

OS: OSX El Capitan 10.11.3 (15D21)
Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by buu700** [comment]
Hi Mickael, thanks for looking out for this sort of thing! Any watchful eyes on potential security issues are much appreciated.

In this case, what you're seeing isn't actually a bug, but rather an intended (albeit complicated and confusing) side effect of [WebSign](https://cyph.team/websigndoc), Cyph's in-browser code signing layer.

Ctrl+Fing "incognito" in that document will explain exactly what's going on here. (We should probably add something about that to the cyph.com FAQ, now that I think about it.)

As far as preloading, cyph.ws uses HSTS preloading, which only ensures that all requests to http://cyph.ws will be redirected to https://cyph.ws by the browser locally (without needing to first look at a potentially malicious redirect instruction sent over plaintext HTTP); HPKP preloading, which might cause something like what you observed, is not used (as it would be incompatible with WebSign's "HPKP Suicide" technique).

Also, just to clarify, is it only incognito where the page is blocked from loading (which is expected), or is it also happening in normal browsing sessions?

**Comment by Mickael-van-der-Beek** [comment]
@buu700 Thanks for the quick answer.

I understand the issue at hand now. Originally I though it had to do with HSTS preloading and caching.

We have one case on a brand new OSX, where even in normal mode on Chrome the site gets the same `NET::ERR_SSL_PINNED_KEY_NOT_IN_CERT_CHAIN` error.

OS: OSX sierra 10.12.5 (16F2073)
Browser: Chrome Version 59.0.3071.115 (Official Build) (64-bit)

The Chrome version is the same as mine and since this browser uses it's own certificate repository instead of the operating system's repository (I think), I wonder what the underlying issue is.
Without having a super in-depth view of the problem I would still guess that it has something to do with older systems that have already browsed to cyph.ws before this Chrome change was made and cached the certificate chain.

**Comment by buu700** [comment]
Hmm, well that's interesting. Did that happen the very first time Cyph was used on that machine, or did it briefly work before the problem started?

Can you send a screenshot of the listing for cyph.ws in chrome://net-internals/#hsts in that browser? That'll include a timestamp of when the TLS key was pinned with HPKP. Also, is there anything listed on chrome://serviceworker-internals or chrome://appcache-internals? (Nothing Cyph-related should be listed there if it's having this problem, but I'm curious about whether there's anything there at all.)

**Comment by Mickael-van-der-Beek** [comment]
@buu700 Thanks for coming back on the issue this fast.
Results are:

- chrome://appcache-internals, is empty for cyph.ws
- chrome://serviceworker-internals, has one entry but for cyph.im

![screen shot 2017-07-19 at 12 22 14 pm](https://user-images.githubusercontent.com/4224802/28366559-87468402-6c8d-11e7-9209-cbd71ae43ea4.png)

- chrome://net-internals/#hsts, has one entry for cyph.ws

![screen shot 2017-07-19 at 12 21 14 pm](https://user-images.githubusercontent.com/4224802/28366573-a2005a34-6c8d-11e7-86e2-6a4a857d689a.png)

Hope that helps.

**Comment by buu700** [comment]
Hmm. What's the actual error you're seeing when you go to cyph.ws on that machine, and what does the certificate look like? There's no pinning timestamp there, so you may just have an actual TLS MitM that's completely unrelated to the error you saw in incognito mode.

**Comment by Mickael-van-der-Beek** [comment]
@buu700 Alright, well sorry to disappoint but somehow the problem solved itself. The person using that computer didn't change any setting but it works now. I have no idea why though. Maybe it's linked to a certain certificate's start date / expiration date?
In any case, thank you for the support.

**Comment by buu700** [comment]
Ah, got it, not a problem. It would've been nice if they'd gotten a chance to try visiting some other site with HPKP enabled (for example, off the top of my head, GitHub).

From what you sent here, it sounds like the issue might not have been related to Cyph/WebSign at all (aside from the key rotation/pinning making your investigation a lot more confusing), but rather something actually performing a TLS MitM and neglecting to modify/remove HPKP headers. This could be due to any number of things, including:

* Local malware

* An attack over the network (from someone who'd compromised a certificate authority)

* A broken/insecure feature of a lot of antivirus software packages (e.g. Kaspersky) that intentionally performs a local MitM

* Corporate intranet web filter (intentionally configured on each device as a root CA)

* A local MitMing proxy (e.g. Burp Suite) could've been accidentally running

That wouldn't explain why it's working now, though, aside from the MitM either stopping or having its HPKP problem fixed.

Also, when you sent that screenshot earlier, do you know whether or not the Cyph problem was still happening? If it wasn't confirmed to still be happening, you can probably disregard all of the above. In that case, it might have fixed itself as a result of the user clearing their cache (which also clears pinned TLS keys in Chrome).

**Comment by Mickael-van-der-Beek** [comment]
@buu700 They were definitely able to access GitHub. So the issue wasn't happening for every HPKP website.

- local malware, seems unlikely on a fresh OSX laptop
- attack over the network, possible but we're working behind a NAT + firewall
- antivirus, there wasn't any antivirus software on that machine at the time
- intranet filter, possible but we haven't seen one yet so my knowledge there isn't one and also fresh install don't having anything preinstalled by us
- MitM proxy, we use various proxies and a VPN but no forwarding MitM to my knowledge either

And indeed, at the time, to my knowledge the issue was still there.

It's a non-issue now that it solved itself though. Thanks in any case.

**Comment by buu700** [comment]
Cool, thanks again for all the information. I don't have any really good guesses at this point as to what could've happened, but I'll keep an eye out for issues like this in case there is an edge case bug or something that we need to fix.
