### ISSUE TITLE
Not working for audio calls between two machines running OSX

### ISSUE THREAD

**Issue by markNZed** [cyph/cyph#56]
On one machine we have sound and on the other no sound. On the machine with no sound there is a spinning circle. We can send video from the machine with no sound to the other machine. Text messages work in both directions.

**Comment by buu700** [comment]
Thanks for the report! We'll do some testing to see if we can reproduce the problem at all, and we're looking into a potential performance/reliability improvement for voice/video calling that may help mitigate this general type of issue.

**Comment by buu700** [comment]
Hey, any idea if this is still an issue? A number of improvements and edge case fixes have been put in since this ticket was opened, so I'll go ahead and close this for now until it happens again.
