### ISSUE TITLE
Firebase rules reference a non existing variable $DOMAIN

### ISSUE THREAD

**Issue by omer88** [cyph/cyph#57]
Firebase rules are not compiled because they reference a non existing variable $DOMAIN.
From what I saw it occurred due to this [commit](https://github.com/cyph/cyph/commit/192426c857457e51e2fa4e52d0bf4e0fbc93829b).
It looks like the variable $namespace in the hierarchy should be replaced with $DOMAIN.

**Comment by buu700** [comment]
Thanks for the report! `$DOMAIN` is actually replaced by our deploy script with the correct value — which is just `$namespace.replace(/_/g, '.')`, but Realtime Database rules don't seem to make this possible to express in a straightforward way. How'd you end up noticing that?
