### ISSUE TITLE
Reporting potential security vulnerabilites

### ISSUE THREAD

**Issue by theevilbit** [cyph/cyph#68]
Hi,

How can someone report a security issue? This is my 3rd attempt to do it. I tried email, submit a bug ticket, and now here. So far no response to the rest.

I would stay away from putting it here publicly, unless no one comes back to me.

Csaba

**Comment by theevilbit** [comment]
Hi,

Thanks. Sent a message via: https://cyph.app/#compose/user/cyph
Let me know if you got it.
The PGP key seem to be for: websign@cyph.com

Csaba

**Comment by theevilbit** [comment]
Hi @JoshBoehm 

Did you receive my submission?

Thanks,
Csaba

**Comment by buu700** [comment]
Thanks for the report Csaba! Just replied over email.
